### PR TITLE
Pretty warning when one or more characters are duplicates in the charset

### LINKED ISSUE #2: Crashes upon running encoding with a string with two of the same letter
image

image

### PR DESCRIPTION
**Pull request by xplshn**
This PR fixes https://github.com/quackduck/aces/issues/2

### CODE REVIEW

**Comment by quackduck** [comment]
Should this be just a warning or a full error? I'm on the side of making this a fatal error.

**Comment by xplshn** [comment]
But what if someone wants to use `aces` in a script where the charset may be determined by the user or data that could contain repetitions?

Anyways, its up to you to decide this. The first commit makes it a fatal error, the second I thought about the case I just mentioned and decided to make it a warning

**Comment by quackduck** [comment]
> But what if someone wants to use aces in a script where the charset may be determined by the user or data that could contain repetitions?

Repeats in a charset make it impossible to decode data. Think of what would happen if two digits looked the exact same: you'd never be sure what number you actually have.

**Comment by xplshn** [comment]
Its up to you to decide what to do, the warning could be made into an error and use a simple global bool to have it be a warning in lax situations

**Pull request closed without merging**
