### PR TITLE
Init flake

### PR DESCRIPTION
**Pull request by anirudhb**
Adds a flake, so we can add this to the hack club nix overlay :)

### CODE REVIEW

**Comment by quackduck** [comment]
Does this work on windows too?

**Comment by quackduck** [comment]
How would updating the flake work?

**Comment by anirudhb** [comment]
Nix doesn't work on windows, also the flake doesn't need to be updated, as it will build from the current source repository.

**Comment by quackduck** [comment]
Alright, thanks a lot

**Pull request merged**
